users:
  root:
    password: "1234"
  microrat:                              # 非 root 用户自动加入 sudo/video/render/input/tty 组
    password: "1"

display:
  max_resolution: "1920x1080@60"   # RK3588 性能限制，不超过 1080p@60Hz

custom_debs:
  enabled: true                    # 设为 true 时安装 configs/rootfs/debs/ 下的所有 .deb 包

network:
  wlan0:
    ssid: "OpenWrt_5G1"          # 预设 WiFi 名称
    password: "12345678"         # 预设 WiFi 密码
  eth0:
    mode: "static"               # 支持 static / dhcp
    address: "192.168.10.100"    # static 模式必填
    netmask: "255.255.255.0"     # 可选，也可改用 prefix: "24"
    gateway: "192.168.10.1"      # 可选
  eth1:
    mode: "dhcp"

ros2:
  enabled: true                    # 设为 true 时在 RootFS 构建期间自动安装 ROS 2
